### PR TITLE
Validiate responses

### LINKED ISSUE #18: Crash when listing robots
Hi!

Gets this message when I try to use the code:
```

$ python3
Python 3.5.2 (default, Nov 23 2017, 16:37:01) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from pybotvac import Account
>>> for robot in Account('hermansson.patrik@gmail.com', '<hidden>').robots: print(robot)
... 
/usr/lib/python3/dist-packages/urllib3/connection.py:266: SubjectAltNameWarning: Certificate for nucleo.neatocloud.com has no `subjectAltName`, falling back to check for a `commonName` for now. This feature is being removed by major browsers and deprecated by RFC 2818. (See https://github.com/shazow/urllib3/issues/497 for details.)
  SubjectAltNameWarning
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/pybotvac/account.py", line 64, in robots
    self.refresh_robots()
  File "/usr/local/lib/python3.5/dist-packages/pybotvac/account.py", line 108, in refresh_robots
    traits=robot['traits']))
  File "/usr/local/lib/python3.5/dist-packages/pybotvac/robot.py", line 37, in __init__
    if self.service_version not in SUPPORTED_SERVICES:
  File "/usr/local/lib/python3.5/dist-packages/pybotvac/robot.py", line 150, in service_version
    return self.available_services['houseCleaning']
  File "/usr/local/lib/python3.5/dist-packages/pybotvac/robot.py", line 146, in available_services
    return self.state['availableServices']
  File "/usr/local/lib/python3.5/dist-packages/pybotvac/robot.py", line 142, in state
    return self.get_robot_state().json()
  File "/usr/local/lib/python3.5/dist-packages/pybotvac/robot.py", line 118, in get_robot_state
    return self._message({'reqId': "1", 'cmd': "getRobotState"})
  File "/usr/local/lib/python3.5/dist-packages/pybotvac/robot.py", line 55, in _message
    headers=self._headers)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 107, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 53, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 454, in request
    prep = self.prepare_request(req)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 388, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/usr/lib/python3/dist-packages/requests/models.py", line 297, in prepare
    self.prepare_auth(auth, url)
  File "/usr/lib/python3/dist-packages/requests/models.py", line 490, in prepare_auth
    r = auth(self)
  File "/usr/local/lib/python3.5/dist-packages/pybotvac/robot.py", line 170, in __call__
    signing = hmac.new(key=self.secret.encode('utf8'),
AttributeError: 'NoneType' object has no attribute 'encode'

```

I have two robots listed at my Neato account.

### PR DESCRIPTION
**Pull request by Santobert**
There have been some errors recently that indicate that neatos API is not behaving according to their documentation. For this reason, we are now validating all responses. This is not disruptive for now, as all errors in `robot.py` are logged and then ignored. Only errors that occur in `account.py` will stop the further process as it makes no sense to continue with invalid data.

Relevant issues:
- https://github.com/home-assistant/core/issues/44709
- https://github.com/home-assistant/core/issues/44709#issuecomment-755814436
- https://github.com/home-assistant/core/issues/43889
- https://community.home-assistant.io/t/2021-1-happy-new-year/264975/77
- https://community.home-assistant.io/t/new-neato-integration-installation-guide-oauth2-for-ha-version-2021-1/265177/24

Closes: #18 

~~Still a draft, as extensive testing is required~~ I think we can merge this. At least to solve the issues listed above as soon as possible. @dshokouhi What do you think?

### CODE REVIEW

**Comment by ahknight** [comment]
As requested in https://github.com/home-assistant/core/issues/44709#issuecomment-758117765, here's the output on an account with a robot that has a bad response (note I added a `pprint` line to `def state` so it appears twice; that's a local change):

```
Robots:
Invalid response from https://nucleo.neatocloud.com/vendors/neato/robots/GPC3XXXX-XXXXXXXXXXXX/messages: required key not provided @ data['availableServices']. Got: {'version': 1, 'reqId': '1', 'result': 'ok', 'data': {}}
<Response [200]>
Your robot Upstairs is unsupported.
<Response [200]>
Name: Downstairs, Serial: OPS4XXXX-XXXXXXXXXXXX, Secret: A...0 Traits: ['maps', 'persistent_maps']

<Response [200]>
{'action': 13,
 'alert': 'dustbin_full',
 'availableCommands': {'goToBase': False,
                       'pause': False,
                       'resume': False,
                       'start': False,
                       'stop': False},
 'availableServices': {'IECTest': 'advanced-1',
                       'findMe': 'basic-1',
                       'generalInfo': 'basic-1',
                       'houseCleaning': 'basic-4',
                       'logCopy': 'basic-1',
                       'manualCleaning': 'basic-1',
                       'maps': 'basic-2',
                       'preferences': 'basic-2',
                       'schedule': 'basic-2',
                       'softwareUpdate': 'basic-1',
                       'spotCleaning': 'basic-3',
                       'wifi': 'basic-1'},
 'cleaning': {'category': 4,
              'mapId': '',
              'mode': 1,
              'modifier': 1,
              'navigationMode': 1,
              'spotHeight': 0,
              'spotWidth': 0},
 'data': {},
 'details': {'charge': 96,
             'dockHasBeenSeen': False,
             'isCharging': False,
             'isDocked': False,
             'isScheduleEnabled': True},
 'error': 'gen_picked_up',
 'meta': {'firmware': '4.5.3-189', 'modelName': 'BotVacD7Connected'},
 'reqId': '1',
 'result': 'ok',
 'state': 4,
 'version': 1}
State:
 {'version': 1, 'reqId': '1', 'result': 'ok', 'data': {}, 'error': 'gen_picked_up', 'alert': 'dustbin_full', 'state': 4, 'action': 13, 'cleaning': {'category': 4, 'mode': 1, 'modifier': 1, 'navigationMode': 1, 'mapId': '', 'spotWidth': 0, 'spotHeight': 0}, 'details': {'isCharging': False, 'isDocked': False, 'isScheduleEnabled': True, 'dockHasBeenSeen': False, 'charge': 96}, 'availableCommands': {'start': False, 'stop': False, 'pause': False, 'resume': False, 'goToBase': False}, 'availableServices': {'findMe': 'basic-1', 'generalInfo': 'basic-1', 'houseCleaning': 'basic-4', 'IECTest': 'advanced-1', 'logCopy': 'basic-1', 'manualCleaning': 'basic-1', 'maps': 'basic-2', 'preferences': 'basic-2', 'schedule': 'basic-2', 'softwareUpdate': 'basic-1', 'spotCleaning': 'basic-3', 'wifi': 'basic-1'}, 'meta': {'modelName': 'BotVacD7Connected', 'firmware': '4.5.3-189'}}

<Response [200]>
Schedule enabled: True
Disabling schedule
<Response [200]>
Schedule enabled: False
Enabling schedule
<Response [200]>
Schedule enabled: True

```

**Review by dshokouhi — APPROVED** [review]
Looks good to me, tested in HA dev branch

**Comment by Santobert** [comment]
Thanks @ahknight. The behavior is as intended. First we try to fetch the robot state. As we can see, the invalid response was logged. Then we try to use this state. Since it' s invalid, we log that too that and skip that robot. The other one works as expected and remains usable.

**Comment by Santobert** [comment]
I'll fix these conflicts right now. Just give me 2 minutes

**Comment by Santobert** [comment]
@stianaske ~~I'll fix these conflicts right now. Just give me 2 minutes~~ nvm :laughing:

**Pull request merged**
