### PR TITLE
Zone cleaning

### LINKED ISSUE #31: Zone Cleaning
I figured since a few of us with D7's have gotten zoned cleaning that we can use this issue to report on the data we have seen and how to best add zoned cleaning.  Just now I was able to pull the botvac state while it was cleaning a specific zone and it seems like the user may need to do their own research to get the proper variables in place.

Here is the state output

`
{'version': 1, 'reqId': '1', 'result': 'ok', 'data': {}, 'error': None, 'alert': None, 'state': 2, 'action': 11, 'cleaning': {'category': 4, 'mode': 2, 'modifier': 1, 'navigationMode': 1, 'mapId': '2018-06-26T02:45:10Z', 'boundary': {'id': '009cdabd-5b38-4804-bdf2-da7de2e3f2d7', 'name': 'Hallway'}, 'spotWidth': 0, 'spotHeight': 0}, 'details': {'isCharging': False, 'isDocked': False, 'isScheduleEnabled': False, 'dockHasBeenSeen': True, 'charge': 94}, 'availableCommands': {'start': False, 'stop': True, 'pause': True, 'resume': False, 'goToBase': True}, 'availableServices': {'findMe': 'basic-1', 'generalInfo': 'basic-1', 'houseCleaning': 'basic-4', 'IECTest': 'advanced-1', 'logCopy': 'basic-1', 'manualCleaning': 'basic-1', 'maps': 'basic-2', 'preferences': 'basic-1', 'schedule': 'basic-2', 'softwareUpdate': 'basic-1', 'spotCleaning': 'basic-3', 'wifi': 'basic-1'}, 'meta': {'modelName': 'BotVacD7Connected', 'firmware': '4.3.1-180'}}
`

Major differences I see here is that `mapId` is required whereas before with `category: 4` it would take the latest floorplan.  I am not sure how we can get the boundary `id` without using pybotvac but the `name` is something the user will know.  

Will need to play around with the above parameters to see exactly what we need to give.

If anyone has any ideas on how we can retrieve the boundary `id` and `mapId` easily that would be great, the only way I can think of for now is to run individual zone cleanings to get the proper data.

When I get a chance to play with this more I will report back but lets make sure the data lines up with everyone else :)

### PR DESCRIPTION
**Pull request by esteve**
This adds support for zone cleaning. The list of boundary ids can be obtained by calling `get_map_boundaries`.

Depends on #32 

Fixes #31

### CODE REVIEW

**Comment by esteve** [comment]
Same disclaimer as with https://github.com/stianaske/pybotvac/pull/32#issuecomment-447404297, none of this is documented on Neato's SDK, so I had to reverse engineer the API, I'm not sure about the correctness of this PR.

**Comment by stianaske** [comment]
Looks great. Merged into [dev ](https://github.com/stianaske/pybotvac/tree/dev) branch together with #20, #32 and #34 for now. Will do some more testing before merging [dev](https://github.com/stianaske/pybotvac/tree/dev) to [master](https://github.com/stianaske/pybotvac/tree/master).

It would be great if you guys with robots that actually support persistent maps check that everything seems to be working fine before I merge.

**Comment by dshokouhi** [comment]
@stianaske I ran some tests in my own environment and so far so good, Was able to initiate a normal cleaning job and also run zone cleaning. 

If anyone wants to try using Home Assistant directly I created a separate branch however it does require you to interact with pybotvac to grab the necessary data.

https://github.com/dshokouhi/hass-neato-custom-component/tree/zone_cleaning

**Comment by dshokouhi** [comment]
Looks like the D7s got another update to 4.4, the changes are still working fine from the dev branch.

**Comment by esteve** [comment]
@stianaske some of the changes I made in this PR didn't land in master because an older version of this branch was merged into dev (which was merged into master). How should I proceed here? Should I close this pull request and open a new one with the missing changes? Should pull requests target dev instead? Thanks.

**Comment by stianaske** [comment]
@esteve If you could make a new PR that would be great. Otherwise, I can look into resolving the conflicts myself.

**Comment by chemelli74** [comment]
@stianaske are you considering merging this great functionality ?

I may help if you want ;-)

Simone

**Comment by dshokouhi** [comment]
>  are you considering merging this great functionality ?
> 
> I may help if you want ;-)
> 
> Simone

@chemelli74 Zone cleaning has been a thing for a while now, its also supported in HA.  I think this is just  an old PR

https://github.com/stianaske/pybotvac/blob/master/pybotvac/robot.py#L197

https://www.home-assistant.io/integrations/neato#service-neatocustom_cleaning

https://github.com/stianaske/pybotvac/commit/70dec30df929b48060b2be41c313c6c38e25b2fd#diff-d0a2380766aafc1d726005d1dd56df323a65d411a9db4e14a597262639c3f318

**Comment by chemelli74** [comment]
> @chemelli74 Zone cleaning has been a thing for a while now, its also supported in HA. I think this is just an old PR

I was under the impression that this PR was able to extract the list of the zones so to have then ready to use instead of writing them by hand.
Am I wrong ?

Simone

**Comment by dshokouhi** [comment]
> > @chemelli74 Zone cleaning has been a thing for a while now, its also supported in HA. I think this is just an old PR
> 
> I was under the impression that this PR was able to extract the list of the zones so to have then ready to use instead of writing them by hand.
> Am I wrong ?
> 
> Simone
>  

If you enable debug logging for the integration and you will see a list of boundaries printed. The list is already there just needs to be utilized inside HA ☺️

**Comment by chemelli74** [comment]
> If you enable debug logging for the integration and you will see a list of boundaries printed. The list is already there just needs to be utilized inside HA ☺️

Ahahahah, indeed it is.
But Why not offer a list from the library to HA ?
Is so user friendly to add/remove/rename zones without dealing with yaml ;-)

**Comment by dshokouhi** [comment]
> > If you enable debug logging for the integration and you will see a list of boundaries printed. The list is already there just needs to be utilized inside HA ☺️
> 
> Ahahahah, indeed it is.
> But Why not offer a list from the library to HA ?
> Is so user friendly to add/remove/rename zones without dealing with yaml ;-)
> 
> 

That's a bit of of scope for what was done here though. You can always submit a PR to do what you want. I was just letting you know what you want is already provided.

**Comment by chemelli74** [comment]
I understand your position.

But  I think that `get_map_boundaries`, part of this PR, is the first step for getting a list.
Or do I miss something ?

Thx for your time,

Simone

**Comment by dshokouhi** [comment]
> I understand your position.
> 
> But  I think that `get_map_boundaries`, part of this PR, is the first step for getting a list.
> Or do I miss something ?
> 
> Thx for your time,
> 
> Simone

Yes that's the data directly from the neato API

https://developers.neatorobotics.com/api/robot-remote-protocol/maps

So first need to get list of maps, then this call will return the zones and boundaries for the specified map. So if a user has multiple maps it needs to be looped through to get all the zones. 

Initially I tried adding the list of zones as an attribute but that was denied by HA devs. So we opted to use the name that the user set in the neato app since that is where the zones get generated from.

**Comment by chemelli74** [comment]
Hi again @dshokouhi!

We now have what we need: [New entity: Select](https://www.home-assistant.io/blog/2021/07/07/release-20217/#new-entity-select)

Simone

**Comment by stianaske** [comment]
Closing this due to conflicts.
The main functionality in this PR was included in a previous merge, but I believe this exact PR has some additional changes that were not included (my bad). Please submit a new PR if the remaining changes should be included.

**Pull request closed without merging**
